name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: chandakanant
      REGISTRY: ghcr.io
      TAG: jenkins-multi-arch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.2.1
          
      
      - name: Login to gHCR
        run: echo $PAT | docker login ${{ env.REGISTRY }} -u ${{ env.USER }} --password-stdin
        
      - name: Build the Docker image
        run: docker buildx build --push -t ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:multiarch --platform linux/amd64,linux/arm64 .
          
#       - name: Login to gHCR
#         run: |
#           echo $PAT | docker login ${{ env.REGISTRY }} -u ${{ env.USER }} --password-stdin
#           docker tag $TAG ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:multiarch
#           docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:multiarch
        
        
