name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: chandakanant
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag jenkins --platform linux/amd64,linux/arm64
        
      - name: Login to gHCR
        run: |
          echo $PAT | docker login ${{ env.REGISTRY }} -u ${{ env.USER }} --password-stdin
          docker tag jenkins:multiarch ${{ env.REGISTRY }}/${{ env.USER }}/jenkins
          docker push ${{ env.REGISTRY }}/${{ env.USER }}/jenkins
        
        
