name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: chandakanant
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get tag
        id: repository
        run: echo "tag=$(git describe --tags jenkins-multiarch)" > $GITHUB_ENV
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.2.1
          
#       - name: Build the Docker image
#         run: docker buildx build -t jenkins --platform linux/amd64,linux/arm64 .
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.tag }}
          
#       - name: Login to gHCR
#         run: |
#           echo $PAT | docker login ${{ env.REGISTRY }} -u ${{ env.USER }} --password-stdin
#           docker tag jenkins ${{ env.REGISTRY }}/${{ env.USER }}/jenkins:multiarch
#           docker push ${{ env.REGISTRY }}/${{ env.USER }}/jenkins:multiarch
        
        
